trigger:
  branches:
    include:
    - 'master'

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  tag: 'docker-stable-powershell-7.0.2'

steps:
- script:
    docker build -t dmitriyafonin/dind-powershell:$(tag) .
  displayName: Building an image

- script: 
    docker login -u $(docker_user) -p $(docker_pass)
  displayName: Logging to docker hub

- script:
    docker push dmitriyafonin/dind-powershell:$(tag)
  displayName: Pushing an image