trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - '*'

pool:
  vmImage: 'Ubuntu-16.04'


steps:
- script:
    tag=$(git describe --exact-match $(Build.SourceVersion))
    docker build -t dind-powershell:${tag}
  displayName: Building an image

- script:
    tag=$(git describe --exact-match $(Build.SourceVersion))
    docker login -u $(docker_user) -p $(docker_pass)
  displayName: Logging to docker hub

- script:
    tag=$(git describe --exact-match $(Build.SourceVersion))
    docker push dind-powershell:${tag}
  displayName: Pushing an image