trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - '*'

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  tag: '1.0.0'

steps:
- script: 
    docker build -t dind-powershell:$(tag)
  displayName: Building an image

- script: 
    docker login -u $(docker_user) -p $(docker_pass)
  displayName: Logging to docker hub

- script:
    docker push dind-powershell:$(tag)
  displayName: Pushing an image